export * from "./types/index";
export * from "./schemas/index";
export * from "./constants";
export * from "./data/index";
export * from "./builders/index";
// Re-export 5etools utils (avoid conflicts with data/index getCasterMultiplier)
export {
  SCHOOL_MAP,
  SIZE_MAP,
  DMG_TYPE_MAP,
  FEAT_CAT_MAP,
  ITEM_TYPE_MAP,
  OPT_FEAT_TYPE_MAP,
  CR_XP_MAP,
  ABILITY_MAP,
  ABILITY_ABBR,
  PROPERTY_MAP,
  formatSchool,
  formatCastingTime,
  formatRange,
  formatComponents,
  formatDuration,
  isConcentration,
  isRitual,
  formatSpellLevel,
  formatMonsterSize,
  formatMonsterType,
  formatMonsterAc,
  formatMonsterHp,
  formatMonsterSpeed,
  formatMonsterCr,
  crToNumber,
  crToXp,
  getAbilityScores,
  formatAbilityMod,
  formatSaves,
  formatSkills,
  flattenResistances,
  flattenConditionImmunities,
  getHitDice,
  getHitDiceFaces,
  getSavingThrows,
  getArmorProfs,
  getWeaponProfs,
  getToolProfs,
  getSkillChoices,
  getCasterType,
  getSpellSlotTable,
  getPactSlotTable,
  formatFeatCategory,
  formatPrerequisite,
  formatSpeciesSize,
  getSpeciesSpeed,
  getBackgroundSkills,
  getBackgroundTools,
  getBackgroundFeat,
  getBackgroundAbilityScores,
  formatItemCost,
  formatDamageType,
  decodeProperty,
  decodeMastery,
  decodeItemType,
  categorizeBaseItem,
  formatOptionalFeatureType,
  parseTags,
  stripTags,
  entriesToText,
} from "./utils/5etools";
export type { ParsedTag } from "./utils/5etools";
